### ISSUE TITLE
Infografía-Blanca Estela

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-2-infografia-Blanca-estela-valerio-rivero#1]
[Infografia-Blanca Estela.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-Blanca-estela-valerio-rivero/files/9474390/Infografia-Blanca.Estela.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by gilbertovelasco1** [comment]
17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
